- name: install kibana package
  apt: name={{ item }} state=installed
  with_items:
  - kibana
  when: kibana_use_repository

- name: download kibana package from url
  get_url: url={% if kibana_custom_package_url is defined %}{{ kibana_custom_package_url }}{% else %}{{ kibana_package_url }}-{{ kibana_version }}.deb{% endif %} dest=/tmp/kibana-{{ kibana_version }}.deb validate_certs=no
  when: not kibana_use_repository

- name: Debian - Ensure kibana is installed from downloaded package
  apt: deb=/tmp/kibana-{{ kibana_version }}.deb
  when: not kibana_use_repository
